version: "3"

services:

  client_web:
    build:
      context: "./client_web"
      args:
        API_URL: https://api.thecountofmoney.nuage.best/api
    ports:
      - "3000:3000"
    networks:
      - default
    restart: always
    depends_on:
      - api
    command:
      "npm run start"

  api:
    build: "./api"
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - default
    environment:
      - PORT=8081
      - DB_URL=mongodb://mongodb-com
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb-api
    restart: on-failure

  mongodb-api:
    image: mongo:latest
    container_name: mongodb-com
    expose:
      - 27017
      - 35496
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - mongo-volume-com:/data/db
    networks:
      - default
    environment:
      - PORT=27017

networks:
  default:

volumes:
  mongo-volume-com:
