name: Deploy

on:
  workflow_run:
    workflows: ["Project"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: Deploy on VPS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "."
        target: "TheCountOfMoney"

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command_timeout: 15m
        script: |
          ./thecountofmoney.sh
